k9s:
  cluster: kubernetes
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - default
  view:
    active: svc
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
