k9s:
  cluster: default
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - default
  view:
    active: po
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
